version: "3.7"

services:
  app:
    image: php:7.2-apache
    ports:
      - 8000:80
    volumes:
      - ./dist/:/var/www/html/
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secrets
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: