version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: php:8.1.1-apache
    ports:
      - 8000:80
    volumes:
      - ./dist/:/var/www/html/
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secrets
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secrets
      MYSQL_DATABASE: todos
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  todo-mysql-data: null

# agregar phpmyadmin
# https://www.section.io/engineering-education/dockerized-php-apache-and-mysql-container-development-environment/
